// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRAnalyzerApi.Models;

#nullable disable

namespace PRAnalyzerApi.Migrations
{
    [DbContext(typeof(PRAnalyzerDbContext))]
    partial class PRAnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PRAnalyzerApi.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Develope__3214EC0724BFAFDB");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.IssueDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__IssueDom__3214EC075A3F4BBD");

                    b.ToTable("IssueDomains");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Prdiagnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRFileId");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__PRDiagno__3214EC076F790369");

                    b.HasIndex("DomainId");

                    b.HasIndex("PrfileId");

                    b.ToTable("PRDiagnostics", (string)null);
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Prfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__PRFiles__3214EC076F0593CA");

                    b.HasIndex("PullRequestId");

                    b.ToTable("PRFiles", (string)null);
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.PullRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AsigneesCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__PullRequ__3214EC071D1C9C0D");

                    b.HasIndex("DeveloperId");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Prdiagnostic", b =>
                {
                    b.HasOne("PRAnalyzerApi.Models.IssueDomain", "Domain")
                        .WithMany("Prdiagnostics")
                        .HasForeignKey("DomainId")
                        .IsRequired()
                        .HasConstraintName("FK__PRDiagnos__Domai__4316F928");

                    b.HasOne("PRAnalyzerApi.Models.Prfile", "Prfile")
                        .WithMany("Prdiagnostics")
                        .HasForeignKey("PrfileId")
                        .IsRequired()
                        .HasConstraintName("FK__PRDiagnos__PRFil__4222D4EF");

                    b.Navigation("Domain");

                    b.Navigation("Prfile");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Prfile", b =>
                {
                    b.HasOne("PRAnalyzerApi.Models.PullRequest", "PullRequest")
                        .WithMany("Prfiles")
                        .HasForeignKey("PullRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__PRFiles__PullReq__3D5E1FD2");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.PullRequest", b =>
                {
                    b.HasOne("PRAnalyzerApi.Models.Developer", "Developer")
                        .WithMany("PullRequests")
                        .HasForeignKey("DeveloperId")
                        .HasConstraintName("FK__PullReque__Devel__3A81B327");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Developer", b =>
                {
                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.IssueDomain", b =>
                {
                    b.Navigation("Prdiagnostics");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.Prfile", b =>
                {
                    b.Navigation("Prdiagnostics");
                });

            modelBuilder.Entity("PRAnalyzerApi.Models.PullRequest", b =>
                {
                    b.Navigation("Prfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
